---
application: "Genapp"
schemaVersion: "applicationDescriptor/0.11.0"
description: "General Insurance"
owner: "DMJTA1"
sources:
- name: "cobol"
  repositoryPath: "Genapp/src/cobol"
  language: "COBOL"
  languageProcessor: "Cobol.groovy"
  fileExtension: "cbl"
  artifactsType: "Program"
  files:
  - name: "lgacdb01"
    type: "CBLCICSDB2"
    usage: "main"
  - name: "lgacdb02"
    type: "CBLDB2"
    usage: "main"
  - name: "lgacus01"
    type: "PLICICS"
    usage: "main"
  - name: "lgacus0b"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgacvs01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgapdb01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgapol01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgapvs01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgastat1"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgdpdb01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgdpol01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgdpvs01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgicdb01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgicdb02"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgicdbbb"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgicus01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgicvs01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgipdb01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgipol01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgipvs01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgsetup"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgstsq"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgtestc1"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgtestp1"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgtestp2"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgtestp3"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgtestp4"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgtwsinq"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgucdb01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgucus01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgucvs01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgupdb01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgupol01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgupvs01"
    type: "UNKNOWN"
    usage: "main"
  - name: "lgwebst5"
    type: "UNKNOWN"
    usage: "main"
- name: "copy"
  repositoryPath: "Genapp/src/copy"
  language: "COBOL"
  languageProcessor: "none"
  fileExtension: "cpy"
  artifactsType: "Include File"
  files:
  - name: "lgcmarea"
    type: "UNKNOWN"
    usage: "private"
  - name: "lgpolicy"
    type: "UNKNOWN"
    usage: "private"
baselines:
- branch: "main"
  type: "release"
  reference: "rel-1.0.0"
  buildid: "baseline"
- branch: "release/rel-1.0.0"
  type: "release"
  reference: "rel-1.0.0"
  buildid: "baseline"
